 // 
 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
 using System.Reflection;
 using System.Runtime.InteropServices;
 [assembly: ComVisible(false)]
 [assembly: AssemblyTitle("Ayala Online Launcher")]
 [assembly: AssemblyProduct("Ayala Online")]
 [assembly: Guid("C086529C-00B2-4713-92BF-ECCDC83D53D4")]
 [assembly: AssemblyVersion("2018.5.8.1417")]
 [assembly: AssemblyFileVersion("2018.5.8.1417")]
 